### ISSUE TITLE
External Unique ID length of 32?

### ISSUE THREAD

**Issue by monnix** [Thermondo/django-heroku-connect-sample#64]
The External Unique ID values that are generated have dashes ('-') in them making the length of these fields 36 not 32...does that cause any issues? 

I ask because the documentation states the fields need to be Text(32)...

As an aside...do I need this External Unique ID field for all tables I map with Heroku Connect, or just the ones that are written to in Heroku?

**Comment by codingjoe** [comment]
Hi @monnix,

hm… interesting. We use a PGs native UUID type. I don't know right now, how Heroku Connect syncs it. I also can't test it right now, since I don't have a HC instance running. @amureki are you currently using the `ExternalID` field? Maybe we need to change the docs, if HC does sync this to SF with dashes. I remember that SF does not have native UUID support.

Best
-Joe

**Comment by monnix** [comment]
@codingjoe, Sorry to add these in the wrong location...I'll use the regular repo next time (unless you can move this and issue [#63]).

Anyway, looking at the Python UUID documentation (https://docs.python.org/3.7/library/uuid.html#uuid.uuid4), shows the generated UUID with the four dashes I refer to. 

I can strip them out if the code will break with them in...please advise.

Thanks.

**Comment by codingjoe** [comment]
Hi @monnix,

well, ok, let me elaborate a bit on UUIDs:

A UUID is 128-bit number. That means a UUID is one out of `2^128` different possible numbers (it's actually slightly less for each UUID version).
Anyhow, any given number can be encoded in different ways. Most commonly base10 — or your regular 0-9 alphabet. However, you can use lager alphabets like base16 (hex) or smaller like base2 (binary). Therefore, a UUID does not "have" dashes, they are just used to display a UUID sometimes. In fact, they are commonly used for "human" interfaces, to separate the bit groups.
In a database however, UUIDs are never stored with dashes, since they are usually not stored as a `Latin1` or `UTF-8` string. If a database supports native UUIDs like Postgres does, it simply stores binaries. If it doesn't Django will use the `hex` version, without dashes. Which — you guessed it — is 32 characters long.

Circling back to Heroku Connect this means, we do have support for Native UUIDs on Database level. Native UUIDs are also supported by Heroku Connect itself. However, Heroku Connect must do a conversion to a regular SF test field. I am currently not sure how they do that.

Did you try to sync a UUID? Did you get any errors?
Best,
-Joe

**Comment by monnix** [comment]
@codingjoe, I didn't get any errors, so it has been working properly...that's good.

Also to clarify, the UUID generator in SF that I'm using isn't provided by them...I coded one up...

Thanks for the clarification.
